# =============================================================================
# Optical Crosstalk (CatSim-style separable kernel)
# =============================================================================
#
# Optical crosstalk in scintillator-based CT detectors: light generated by
# X-ray absorption in one detector element spreads to neighbors before being
# collected by the photodiode (intra-crystal scatter, total internal
# reflection, imperfect optical isolation between pixels).
#
# Model: 2D convolution with a separable 3×3 kernel
#     row_kernel = [α, 1-2α, α]
#     col_kernel = [β, 1-2β, β]
#     K = col_kernel ⊗ row_kernel
# Matches CatSim's CalcOptCrossTalk.py.

import AcceleratedKernels as AK

"""
    OpticalCrosstalkModel

Optical crosstalk model using CatSim-exact separable 3×3 convolution kernels.

# Fields
- `row_coeff::Float64`: Row crosstalk coefficient α (typical: 0.04-0.05)
- `col_coeff::Float64`: Column crosstalk coefficient β (typical: 0.04-0.05)

The center kernel weight is `(1-2α)(1-2β)`; each neighbor gets a fraction
proportional to α and/or β. See `create_optical_crosstalk_kernel`.
"""
struct OpticalCrosstalkModel
    row_coeff::Float64
    col_coeff::Float64
end

"""
    optical_crosstalk_typical()

Typical optical crosstalk for GOS scintillator detector.
Values from CatSim: row=0.045, col=0.040.
"""
optical_crosstalk_typical() = OpticalCrosstalkModel(0.045, 0.040)

"""
    create_optical_crosstalk_kernel(model::OpticalCrosstalkModel)

Create 3×3 separable optical crosstalk kernel as the outer product of the
row and column 1D kernels.
"""
function create_optical_crosstalk_kernel(model::OpticalCrosstalkModel)
    α = model.row_coeff
    β = model.col_coeff

    row_kernel = [α, 1 - 2α, α]
    col_kernel = [β, 1 - 2β, β]

    kernel_2d = col_kernel * row_kernel'
    return kernel_2d
end

"""
    apply_optical_crosstalk!(sinogram, model::OpticalCrosstalkModel) -> sinogram

Apply optical crosstalk to projection-domain sinogram (in-place, GPU-native).

Converts to intensity, applies 3×3 separable convolution, converts back.
"""
function apply_optical_crosstalk!(
    sinogram::AbstractArray{T,3},
    model::OpticalCrosstalkModel;
    ws_output=nothing, ws_kernel=nothing
) where T
    if model.row_coeff ≈ 0 && model.col_coeff ≈ 0
        return sinogram
    end

    n_cols = size(sinogram, 1)
    n_rows = size(sinogram, 2)

    if ws_kernel !== nothing
        kernel = ws_kernel
    else
        kernel_cpu = T.(create_optical_crosstalk_kernel(model))
        kernel = similar(sinogram, 3, 3)
        copyto!(kernel, kernel_cpu)
    end

    output = ws_output !== nothing ? ws_output : similar(sinogram)

    let kernel = kernel, output = output, n_cols = n_cols, n_rows = n_rows
        AK.foreachindex(sinogram) do idx
            idx_0 = Int32(idx - 1)
            col = (idx_0 % Int32(n_cols)) + Int32(1)
            idx_0 = idx_0 ÷ Int32(n_cols)
            row = (idx_0 % Int32(n_rows)) + Int32(1)
            angle = (idx_0 ÷ Int32(n_rows)) + Int32(1)

            acc = zero(T)
            for di in -1:1
                for dj in -1:1
                    src_col = clamp(col + di, Int32(1), Int32(n_cols))
                    src_row = clamp(row + dj, Int32(1), Int32(n_rows))

                    ki = di + 2
                    kj = dj + 2

                    intensity_src = exp(-sinogram[src_col, src_row, angle])
                    acc += intensity_src * kernel[ki, kj]
                end
            end

            output[idx] = -log(max(acc, T(1e-10)))
        end
    end

    copyto!(sinogram, output)
    return sinogram
end

# =============================================================================
# Exports
# =============================================================================

export OpticalCrosstalkModel
export optical_crosstalk_typical
export create_optical_crosstalk_kernel
export apply_optical_crosstalk!
